services:
  nginx:
    image: nginx:latest
    container_name: hm-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - hm-backend
      - hm-frontend
    networks:
      - hm-network
    environment:
      - TZ=Asia/Seoul

  certbot:
    image: certbot/certbot
    container_name: hm-certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - hm-network

  hm-backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: hm-backend
    ports:
      - "8081:8081"
    volumes:
      - ./project_data:/app/project_data
    environment:
      - TZ=Asia/Seoul
    networks:
      - hm-network

  hm-frontend:
    build:
      context: ./FE/honey-morning
      dockerfile: Dockerfile
    container_name: hm-frontend
    ports:
      - "5173:5173"
    environment:
      - TZ=Asia/Seoul
    networks:
      - hm-network

  hm-jenkins:
    image: jenkins/jenkins:lts
    container_name: hm-jenkins
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - /var/jenkinsDir:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JENKINS_OPTS=--prefix=/jenkins
      - TZ=Asia/Seoul
    networks:
      - hm-network

  hm-ai-briefing:
    build:
      context: ./AI/FastAPI/briefing
      dockerfile: Dockerfile
    container_name: hm-ai-briefing
    ports:
      - "8000:8000"
    volumes:
      - ./project_data/crawling_data:/var/data
      - /etc/localtime:/etc/localtime
    networks:
      - hm-network

  hm-ai-quiz:
    build:
      context: ./AI/FastAPI/quiz
      dockerfile: Dockerfile
    container_name: hm-ai-quiz
    ports:
      - "8001:8001"
    networks:
      - hm-network

  hm-ai-music:
    build:
      context: ./AI/FastAPI/music
      dockerfile: Dockerfile
    container_name: hm-ai-music
    ports:
      - "8002:8002"
    networks:
      - hm-network

  hm-ai-topic:
    build:
      context: ./AI/FastAPI/topic
      dockerfile: Dockerfile
    container_name: hm-ai-topic
    ports:
      - "8003:8003"
    volumes:
      - ./project_data/crawling_data:/var/data
      - /etc/localtime:/etc/localtime
    networks:
      - hm-network

networks:
  hm-network:
    external: true