services:
  # # Nginx
  # nginx:
  #   image: nginx:latest
  #   restart: unless-stopped
  #   container_name: hm-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #     - ./data/certbot/conf:/etc/letsencrypt 
  #     - ./data/certbot/www:/var/www/certbot
  #   depends_on:
  #     - backend
  #     - frontend
  #   networks:
  #     - hm-network
  
  # # HTTPS
  # certbot:
  #   image: certbot/certbot
  #   restart: unless-stopped
  #   container_name: hm-certbot
  #   volumes:
  #     - ./data/certbot/conf:/etc/letsencrypt 
  #     - ./data/certbot/www:/var/www/certbot
  #   networks:
  #     - hm-network

  # 백엔드
  hm-backend:
    build:
      context: ./BE
      dockerfile: Dockerfile
    container_name: hm-backend
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://hm-mysql:3306/honeymorning?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: ssafy
      SPRING_DATASOURCE_PASSWORD: ssafy
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATA_REDIS_HOST: hm-redis
      SPRING_DATA_REIDIS_PORT: 6379
    networks:
      - hm-network

  # 프론트엔드
  hm-frontend:
    build:
      context: ./FE/honey-morning
      dockerfile: Dockerfile
    container_name: hm-frontend
    ports:
      - "5173:5173"
    depends_on:
      - hm-backend
    networks:
      - hm-network

# 네트워크 설정
networks:
  hm-network:
    external: true
