SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS alarm;
DROP TABLE IF EXISTS alarm_category;
DROP TABLE IF EXISTS alarm_result;
DROP TABLE IF EXISTS quiz;
DROP TABLE IF EXISTS brief;
DROP TABLE IF EXISTS brief_category;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS topic_model;
DROP TABLE IF EXISTS topic_model_word;
DROP TABLE IF EXISTS word;
DROP TABLE IF EXISTS word_cloud;

SET FOREIGN_KEY_CHECKS = 1;