services:
  database:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: honeymorning
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: ssafy
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    command: redis-server --port 6379
    hostname: redis
    ports:
      - "6379:6379"
