name: Backend CI Pipeline

on:
  push:
    branches:
      - develop
      - refactor
    paths:
      - 'BE/**'
  pull_request:
    branches:
      - develop
      - refactor
    paths:
      - 'BE/**'

jobs:
  build:
    name: Build BE Application
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v3

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: grant execute permission
        working-directory: BE
        run: chmod +x ./gradlew

      - name: build and test BackEnd Spring Boot
        working-directory: BE
        run: ./gradlew clean build